apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  labels:
    app: lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: lab
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: "KrastelKIren"
        - name: REACT_APP_COMPANY_NAME
          value: "ITMO_company"
        ports:
        - containerPort: 3000

---


---

apiVersion: v1
kind: Service
metadata:
  name: lab
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: lab


