apiVersion: v1
kind: Namespace
metadata:
  name: itmo

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: map-config
  namespace: itmo
data:
  REACT_APP_USERNAME: 'KrastelKiren-ConfigMap'
  REACT_APP_COMPANY_NAME: 'ITMO-ConfigMap'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thirdlab
  namespace: itmo
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: thirdlab
  template:
    metadata:
      labels:
        tier: thirdlab
    spec:
      containers:
      - name: thirdlab
        image: ifilyaninitmo/itdt-contained-frontend:master
        envFrom:
        - configMapRef:
            name: map-config

---

apiVersion: v1
kind: Service
metadata:
  name: thirdlab
  namespace: itmo
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    tier: thirdlab

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thirdlab
  namespace: itmo
spec:
  tls:
    - hosts: 
        - thirdlab.itmo
      secretName: thirdlab-tls
  rules:
    - host: thirdlab.itmo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thirdlab
                port:
                  number: 3000
